# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_channel_twitter_create:
    pattern:  /channel/twitter/create
    defaults: { _controller: CampaignChainChannelTwitterBundle:Twitter:create }

campaignchain_channel_twitter_login:
    pattern:  /channel/twitter/create/login
    defaults: { _controller: CampaignChainChannelTwitterBundle:Twitter:login }